import type { TableItem } from './sqliteEngine';

function sanitizeEntityName(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, '_');
}

function sanitizeTypeForMermaid(rawType: string): string {
  if (!rawType) return 'string';
  const t = rawType.replace(/\(.*\)/, '').trim().toLowerCase();
  if (t.includes('int')) return 'int';
  if (t.includes('char') || t.includes('text') || t.includes('clob')) return 'string';
  if (t.includes('real') || t.includes('floa') || t.includes('doub') || t.includes('dec') || t.includes('num')) return 'float';
  if (t.includes('blob')) return 'blob';
  if (t.includes('date') || t.includes('time')) return 'datetime';
  if (t.includes('bool')) return 'boolean';
  return 'string';
}

function sanitizeDBMLType(rawType: string): string {
  if (!rawType) return 'text';
  const clean = rawType.trim().toLowerCase();
  return clean || 'text';
}

/**
 * Generates Mermaid erDiagram DSL from SQLite TableItem models.
 */
export function generateMermaidERD(tables: TableItem[]): string {
  const userTables = tables.filter((t) => t.type === 'table');
  if (userTables.length === 0) {
    return 'erDiagram\n    EMPTY_DATABASE {\n        string note "No tables found"\n    }';
  }

  const lines: string[] = ['erDiagram'];
  const relationships: string[] = [];
  const entities: string[] = [];

  const tableNames = new Set(userTables.map((t) => t.name));

  for (const table of userTables) {
    const safeSource = sanitizeEntityName(table.name);

    // Foreign keys / relationships
    if (table.foreignKeys && table.foreignKeys.length > 0) {
      for (const fk of table.foreignKeys) {
        if (tableNames.has(fk.table)) {
          const safeTarget = sanitizeEntityName(fk.table);
          const relLabel = fk.from ? `"${fk.from}"` : '"fk"';
          // Target (Parent) 1 to Source (Child) 0..N
          relationships.push(`    ${safeTarget} ||--o{ ${safeSource} : ${relLabel}`);
        }
      }
    }

    // Entity definition
    const entityLines: string[] = [`    ${safeSource} {`];
    const columns = table.columns || [];

    if (columns.length === 0) {
      entityLines.push('        string empty_table');
    } else {
      for (const col of columns) {
        const colType = sanitizeTypeForMermaid(col.type);
        const colName = sanitizeEntityName(col.name);
        let keyFlag = '';
        if (col.pk) {
          keyFlag = ' PK';
        } else if (col.fk) {
          keyFlag = ' FK';
        }

        const comment = !col.pk && !col.fk && col.notnull ? ' "NN"' : '';
        entityLines.push(`        ${colType} ${colName}${keyFlag}${comment}`);
      }
    }

    entityLines.push('    }');
    entities.push(entityLines.join('\n'));
  }

  // Output relationships first, then entity structures
  if (relationships.length > 0) {
    lines.push(...relationships);
    lines.push('');
  }

  lines.push(...entities);
  return lines.join('\n');
}

/**
 * Generates DBML (Database Markup Language) DSL from SQLite TableItem models.
 */
export function generateDBML(tables: TableItem[]): string {
  const userTables = tables.filter((t) => t.type === 'table');
  if (userTables.length === 0) {
    return '// No user tables found in database\n';
  }

  const output: string[] = [
    '// Database Markup Language (DBML)',
    '// Generated by devtools SQLite Studio',
    '',
  ];

  const refs: string[] = [];
  const tableNames = new Set(userTables.map((t) => t.name));

  for (const table of userTables) {
    output.push(`Table ${table.name} {`);

    for (const col of table.columns || []) {
      const type = sanitizeDBMLType(col.type);
      const settings: string[] = [];

      if (col.pk) settings.push('pk');
      if (col.notnull) settings.push('not null');
      if (col.dflt_value !== null && col.dflt_value !== undefined) {
        settings.push(`default: \`${col.dflt_value}\``);
      }

      const settingsStr = settings.length > 0 ? ` [${settings.join(', ')}]` : '';
      output.push(`  ${col.name} ${type}${settingsStr}`);
    }

    output.push('}');
    output.push('');

    // Foreign keys
    if (table.foreignKeys) {
      for (const fk of table.foreignKeys) {
        if (tableNames.has(fk.table)) {
          const actionParts: string[] = [];
          if (fk.on_delete && fk.on_delete.toUpperCase() !== 'NO ACTION') {
            actionParts.push(`delete: ${fk.on_delete.toLowerCase()}`);
          }
          if (fk.on_update && fk.on_update.toUpperCase() !== 'NO ACTION') {
            actionParts.push(`update: ${fk.on_update.toLowerCase()}`);
          }
          const actions = actionParts.length > 0 ? ` [${actionParts.join(', ')}]` : '';
          refs.push(`Ref: ${table.name}.${fk.from} > ${fk.table}.${fk.to || 'id'}${actions}`);
        }
      }
    }
  }

  if (refs.length > 0) {
    output.push('// Relationships');
    output.push(...refs);
    output.push('');
  }

  return output.join('\n');
}

/**
 * Returns summary stats of the database schema for the ERD viewer.
 */
export function getErdStats(tables: TableItem[]): {
  tableCount: number;
  relationCount: number;
  columnCount: number;
} {
  const userTables = tables.filter((t) => t.type === 'table');
  let relationCount = 0;
  let columnCount = 0;

  for (const t of userTables) {
    relationCount += t.foreignKeys?.length || 0;
    columnCount += t.columns?.length || 0;
  }

  return {
    tableCount: userTables.length,
    relationCount,
    columnCount,
  };
}
